[tool.poetry]
name = "machine-yearning"
version = "0.1.0"
description = ""
authors = ["Caner Mercan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.6"
uvicorn = "^0.32.1"
pathlib = "^1.0.1"
requests = "^2.32.3"
httpx = "^0.28.1"
numpy = "^2.2.0"
torch = { url = "https://download.pytorch.org/whl/cpu/torch-2.6.0%2Bcpu-cp311-cp311-linux_x86_64.whl", markers = "platform_machine == 'x86_64' and platform_python_implementation == 'CPython' and platform_system == 'Linux'" }
torchvision = { url = "https://download.pytorch.org/whl/cpu/torchvision-0.21.0%2Bcpu-cp311-cp311-linux_x86_64.whl", markers = "platform_machine == 'x86_64' and platform_python_implementation == 'CPython' and platform_system == 'Linux'" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
    